server:
  port: 10088
  servlet:
    encoding:
      enabled: true
      charset: utf-8
      force: true

# 配置参考 https://docs.spring.io/spring-ai/reference/api/mcp/mcp-server-boot-starter-docs.html#_webflux_server_configuration
spring:
  main:
    banner-mode: off
  ai:
    # MCP 服务器配置
    mcp:
      server:
        name: my-sse-server # 服务名称
        version: 1.0.0   # 服务版本
        type: ASYNC  # Recommended for reactive applications
        # 配置 sse 的根路径，默认值为 /sse
        # 下面的最终路径为 ip:port/sse/mcp
        sse-endpoint: /sse
        sse-message-endpoint: /mcp
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true