spring:
  main:
    web-application-type: none # 设置为非 Web 应用类型，因为 STDIO 通信不需要 Web 服务器
    banner-mode: off # 关闭 Spring Boot 启动 Banner 输出
  ai:
    # MCP 服务器配置
    mcp:
      server:
        stdio: true # 启用stdio模式
        name: my-weather-server # 服务名称
        version: 1.0.0   # 服务版本
